#!/bin/bash

# Get the title from the command-line arguments
TITLE="$@"

# Get the current date
DATE=$(date +%Y-%m-%d)

# Create the slug
SLUG=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

# Create the filename
FILENAME="_posts/$DATE-$SLUG.markdown"

# Create the file with the front matter
cat << EOF > "$FILENAME"
---
layout: post
title: "$TITLE"
date: $(date +'%Y-%m-%d %H:%M:%S %z')
categories: 
---

EOF

echo "Created new post: $FILENAME"
